name: Website Deployment
on:
 push:
    branches: master
env:
  webapp-name: demodotnetaction         
jobs:
   build:
     runs-on: ubuntu-latest
     steps:
        - name : Get the code
          uses: actions/checkout@v3
        - name : Setup dotnet
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 8.0.x
        - name: Cache dependencies
          uses: actions/cache@v3
          with:
            path: ~/.nuget/packages
            key: cac-dep-${{hashFiles('**/*.csproj')}}
                 
        - name: Restore nuget packages
          run: dotnet restore
        - name: Build the code
          run: dotnet build --no-restore
        - name: Test the code
          run: dotnet test --no-restore
        - name: Publish
          run: dotnet publish  github-demo-app/github-demo-app.csproj -c Release -o website
        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: app
            path: website/**
            if-no-files-found: error
   deploy:
     needs: build
     runs-on: ubuntu-latest
     steps:
        - name: Download the artifact
          uses: actions/download-artifact@v4
          with:
            name: app
            path: ./package
        - name: Deploy in web app
          uses: azure/webapps-deploy@v3
          with:
            app-name: ${{env.webapp-name}}
            publish-profile: ${{secrets.APPSERVICE_PUBLISH_PROFILE}}
            package: ./package
                  
